### ISSUE TITLE
Create mock-ups for the forecasting interface

### ISSUE THREAD

**Issue by alhuelamo** [ADS2018UB/easyrider#16]
Updated on drive:
https://drive.google.com/drive/folders/1vW_rWLh8T-ipHJBtk9Nbw-iTwEpBqK63

**Comment by chris-fady** [comment]
Updated here, "Interface_forecast_mock_up"
https://drive.google.com/drive/folders/1vW_rWLh8T-ipHJBtk9Nbw-iTwEpBqK63
