### ISSUE TITLE
Get journey datasets (several data sources)

### ISSUE THREAD

**Issue by alhuelamo** [ADS2018UB/easyrider#4]

**Comment by jarandaf** [comment]
Chicago dataset retrieved from https://data.cityofchicago.org/Transportation/Divvy-Bicycle-Stations-Historical/eq45-8inv

**Comment by alicjamalota** [comment]
https://data.cityofchicago.org/Transportation/Divvy-Trips/fg6s-gzvg historical dataset related to trips
