### ISSUE TITLE
BUG-Correct the timestamps

### ISSUE THREAD

**Issue by cristina-rosich** [ADS2018UB/easyrider#43]
The timestamps 00.00, 00.10, 00.20, etc should be replaced by 00.05, 00.15, etc. to be rigorous with the data. 
Also, I would put the hour in the station box, just before the -available bikes/-available docks values, to make it more clear.

**Comment by alhuelamo** [comment]
Already fixed dates in the timeline.

**Comment by alhuelamo** [comment]
@aduenape7 can we make the time information permanently visible?

**Comment by alhuelamo** [comment]
@cristina-rosich please, verify to close.
