### ISSUE TITLE
Right panel calendar date and availability tooltip date are out of sync

### ISSUE THREAD

**Issue by jarandaf** [ADS2018UB/easyrider#45]
By default, when clicking on a station, the displayed tooltip date is 1st October. When changing the date by using the calendar on the right panel and leaving the tooltip open, the date is updated correctly, but If we select some other station, the displayed date is again 1st October while the selected date on the right panel is actually different.

![example](https://user-images.githubusercontent.com/2277398/50053538-2a899700-0137-11e9-96ae-cc4075268c47.png)

**Comment by alhuelamo** [comment]
@jarandaf verify to close.

**Comment by jarandaf** [comment]
Thank you for the fix!
