### ISSUE TITLE
Grey section of the map on max zoom out

### ISSUE THREAD

**Issue by chris-fady** [ADS2018UB/easyrider#49]
Possibilities:
- Change default scaling to bigger zoom in
- Load more on launch

**Comment by jarandaf** [comment]
I am afraid we can't do much about it (it is more related to the tiles provider, which in this case is a free one, so we can't expect "high availability").

**Comment by alhuelamo** [comment]
Yes, I think so as well. But maybe we can switch it to Mapbox for the day of the demo. It should be way nicer than with OSM and less cluttered.

**Comment by alhuelamo** [comment]
@chris-fady verify to close
